<?php
$lang = $this->lang;
$page = $this->page;
$paginator = $this->paginator;
?>
<div class="content-container">
	<header class="center"><h1>Transaction List</h1></header>
		<?php foreach ($this->messages as $message): ?>
			<div class="alert alert-warning alert-dismissible center" role="alert">
			<span><?php echo $message; ?></span>
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			</div>
		<?php endforeach; ?>
	<div class="table-responsive">
		<table class="table table-striped table-hover HeaderSellTable">
			<tr>
				<th>ID</th>
				<th>Date</th>
				<th>Casheer</th>
				<th>Customer</th>
				<th>Total</th>
			</tr>
		<?php foreach ($paginator as $headerSell) : ?>
			<tr>
				<td class="center"><?php echo $headerSell->getID(); ?></td>
				<td><?php echo $this->escapeHtml(date('Y-m-d h:m',strtotime($headerSell->getDate()))); ?></td>
				<td><?php echo $this->escapeHtml($this->posDatabasePlugin->getCasheerName($headerSell->getCasheer())); ?></td>
				<td><?php echo $this->escapeHtml($headerSell->getCustomer()); ?></td>
				<td class="right"><?php echo $this->escapeHtml($this->utilityPlugin->toMoney($headerSell->getTotal())); ?></td>
			</tr>
		<?php endforeach; ?>
		</table>
	</div>
	<div class = "center">
		<?= ( count($paginator) > 0 ) ? $this->paginationControl($paginator, 'Sliding', 'pager-sell.phtml', array('lang'=>$lang)) : ""; ?>
	</div>
</div>