<?php
$lang = $this->lang;
$page = $this->page;
$paginator = $this->paginator;
?>
<div class="content-container">
	<header class="center"><h1>Book List</h1></header>
		<?php foreach ($this->messages as $message): ?>
			<div class="alert alert-warning alert-dismissible center" role="alert">
			<span><?php echo $message; ?></span>
			<button type="button" class="close" data-dismiss="alert">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
			</div>
		<?php endforeach; ?>
	<div class="table-responsive">
		<table class="table table-striped table-hover book-table">
			<thead>
				<tr>
					<th>No.</th>
					<th>Book Name</th>
					<th class="right">Stock</th>
					<th class="right">Price</th>
					<th></th>
				</tr>
			</thead>
		<tbody>
		<?php $rowCount = 0; ?>
		<?php foreach ($paginator as $book) : ?>
			<tr>
				<td><?php echo (++$rowCount + ($this->itemCountPerPage * ($this->page-1))); ?></td>
				<td><?php echo $this->escapeHtml($book->getName()); ?></td>
				<td class="right"><?php echo $this->escapeHtml($this->utilityPlugin->thousandSeparator($book->getStock())); ?></td>
				<td class="right"><?php echo $this->escapeHtml($this->utilityPlugin->toMoney($book->getPrice())); ?></td>
				<td class="center">
				<a href="<?php echo $this->url('prepare_edit_entry', array('lang' => $this->lang,'id' => $book->getID())); ?>">Edit</a>
				Delete
				</td>
			</tr>
		<?php endforeach; ?>
		</tbody>
		</table>
	</div>
	<div class="my-pager center">
		<?= ( count($paginator) > 0 ) ? $this->paginationControl($paginator, 'Sliding', 'pager-book.phtml', array('lang'=>$lang)) : ""; ?>
	</div>
</div>